name: transformers
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - numpy
  - matplotlib
  - pip
  - pip:
      - tensorflow
      - tensorflow_datasets
      - boto3
      - sagemaker
